model:
  class_path: modules.PasrModule
  init_args:
    downsample_rates: [2,2,4,4,5]
    downsample_kernel_sizes: [4, 4, 8, 8, 11]
    downsample_initial_channel: 16
    resblock_kernel_sizes: [3,7,11]
    resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
    num_codes: 200
    upsample_initial_channel: 512
    lookahead: 29
# https://pytorch.org/docs/stable/optim.html
optimizer:
  class_path: AdamW
  init_args:
    lr: 5e-4
    weight_decay: 1e-6
# https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
    mode: min
    factor: 0.1
    patience: 3
    verbose: True
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 0
    min_lr: 0.00001
    eps: 1e-08
